server:
  port: 8080

spring:
  application:
    name: mypromethues
  datasource:
    username: root
    password: KhdMcoXgGDRvpJVd
    url: jdbc:mysql://10.18.78.57:3306/wxtest?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    pool:
      enabled: false
  metrics:
    servo:
      enabled: false
  redis:
    host: 127.0.0.1
    port: 6379
redisson:
  address: redis://127.0.0.1:6379
mybatis:
  mapper-locations: classpath:mapping/*.xml
management:
  metrics:
    export:
      prometheus:
        enabled: true
        step: 1m
        descriptions: true
    tags:
      application: ${spring.application.name}
  web:
    server:
      auto-time-requests: true
  endpoints:
    prometheus:
      id: springmetrics
      #对于 Prometheus 来说，Spring Boot Actuator 会自动配置一个 URL 为 /actuator/Prometheus 的 HTTP 服务来供 Prometheus 抓取数据。
      #不过该 Actuator 服务默认是关闭的，需要通过 Spring Boot 的配置打开
    web:
      exposure:
        include: health,info,env,prometheus,metrics,httptrace,threaddump,heapdump,springmetrics

