server:
  port: 8080

spring:
  datasource:
    username: root
    password: KhdMcoXgGDRvpJVd
    url: jdbc:mysql://10.18.78.57:3306/wxtest?useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapping/*.xml
